dist: xenial
language: python
python:
#  - "2.6" # no longer available on travis xenial
  - "2.7"
#  - "3.3" # no longer available on travis xenial
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r tests/requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - pip install codacy-coverage
# command to run tests
script:
  - nosetests
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coverage run -a tests/test_quality.py; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then coverage xml; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'nightly' ]]; then python-codacy-coverage -r coverage.xml; fi
